- hosts: all

  tasks:

    ####
    # Packages
    ####
    - name: Install Homebrew General Packages
      homebrew:
        name: "{{ item }}"
        state: present
        update_homebrew: yes
      with_items:
        - postgres

    ####
    # Concourse Directories
    ####
    - name: Create Concourse Web and Worker Key Directories
      file:
        path: ~/workspace/concourse/keys/{web, worker}
        state: directory
        owner: pivotal
        group: staff
        mode: "u+rwx,go+rx"

    ####
    # Concourse Keys
    ####
    - name: Generate Host Key
      shell: ssh-keygen -t rsa -f tsa_host_key -N ''
      args:
        chdir: ~/workspace/concourse/keys
        creates: tsa_host_key

    - name: Generate Session Signing Key
      shell: ssh-keygen -t rsa -f session_signing_key -N ''
      args:
        chdir: ~/workspace/concourse/keys
        creates: session_signing_key

    - name: Generate Worker Key
      shell: ssh-keygen -t rsa -f worker_key -N ''
      args:
        chdir: ~/workspace/concourse/keys
        creates: worker_key

    - name: Create authorized_keys
      shell: cp worker_key.pub authorized_worker_keys
      args:
        chdir: ~/workspace/concourse/keys
        creates: authorized_worker_keys

    ####
    # Concourse Server & Workers
    ####

    - name: Init Postgres DB
      shell: if [[ -d /usr/local/var/postgres ]]; then echo TRUE ; else echo FALSE; fi
      args:
        creates: /usr/local/var/postgres

    - name: Create Concourse atc Postgres DB
      shell: if [[ -z {{ "$(psql -Atqc '\list atc' postgres)" }} ]]; then createdb -e atc; fi
      register: concourse_atc_result
      changed_when: "concourse_atc_result.stdout != ''"

    - name: Install Concourse Darwin Binary
      get_url:
        url: https://github.com/concourse/concourse/releases/download/v3.5.0/concourse_darwin_amd64
        dest: /usr/local/bin/concourse
        mode: ugo+x,u+rw,g+r

    - name: Install Concourse Web Launchd Service
      copy:
        src: ../launchd/com.pivotal.tokyo.concourse.web.plist
        dest: /Library/LaunchDaemons/com.pivotal.tokyo.concourse.web.plist
      become: true

    - name: Install Concourse Worker Launchd Service
      copy:
        src: ../launchd/com.pivotal.tokyo.concourse.worker.plist
        dest: /Library/LaunchDaemons/com.pivotal.tokyo.concourse.worker.plist
      become: true

    - name: Stop MacOS Concourse Web
      shell: if [[ -n $(launchctl list | grep com.pivotal.tokyo.concourse.web) ]]; then launchctl unload /Library/LaunchDaemons/com.pivotal.tokyo.concourse.web.plist && echo "STOPPING CONCOURSE WEB"; fi
      become: true
      register: launchctl_web_unload_result
      changed_when: "launchctl_web_unload_result.stdout != ''"

    - name: Start MacOS Concourse Web
      shell: launchctl load /Library/LaunchDaemons/com.pivotal.tokyo.concourse.web.plist && echo "STARTING CONCOURSE WEB"
      become: true
      register: launchctl_web_load_result
      changed_when: "launchctl_web_load_result.stdout != ''"

    - name: Stop MacOS Concourse Worker
      shell: if [[ -n $(launchctl list | grep com.pivotal.tokyo.concourse.worker) ]]; then launchctl unload /Library/LaunchDaemons/com.pivotal.tokyo.concourse.worker.plist && echo "STOPPING CONCOURSE WORKER"; fi
      become: true
      register: launchctl_worker_unload_result
      changed_when: "launchctl_worker_unload_result.stdout != ''"

    - name: Start MacOS Concourse Worker
      shell: launchctl load /Library/LaunchDaemons/com.pivotal.tokyo.concourse.worker.plist && echo "STARTING CONCOURSE WORKER"
      become: true
      register: launchctl_worker_load_result
      changed_when: "launchctl_worker_load_result.stdout != ''"
